version: '3.4'

services:
  app:
    image: express-app
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    environment:
      - ./.env
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: ecommerce-db
    ports:
      - 27017:27017

volumes:
  mongo_data:

